proxies:
  - name: "_15"
    type: ss
    server: "198.57.27.218"
    port: 8090
    cipher: aes-256-gcm
    password: "PCnnH6SQSnfoS27"
  - name: "_34"
    type: ss
    server: "167.88.63.99"
    port: 2376
    cipher: aes-256-gcm
    password: "faBAoD54k87UJG7"
  - name: "_36"
    type: ss
    server: "146.70.27.12"
    port: 40093
    cipher: aes-256-gcm
    password: "x23Z4LGkGDkThZ9Kaz4DURQp"
  - name: "_64"
    type: ss
    server: "46.29.218.6"
    port: 8090
    cipher: aes-256-gcm
    password: "PCnnH6SQSnfoS27"
  - name: "_12"
    type: ss
    server: "167.88.63.99"
    port: 2376
    cipher: aes-256-gcm
    password: "faBAoD54k87UJG7"
  - name: "_21"
    type: ss
    server: "167.88.63.82"
    port: 8091
    cipher: aes-256-gcm
    password: "PCnnH6SQSnfoS27"
  - name: "_35"
    type: ss
    server: "167.88.63.82"
    port: 7306
    cipher: aes-256-gcm
    password: "FoOiGlkAA9yPEGP"
  - name: "_43"
    type: ss
    server: "38.107.226.146"
    port: 7306
    cipher: aes-256-gcm
    password: "FoOiGlkAA9yPEGP"
  - name: "Pool__46"
    type: ss
    server: "82.102.26.93"
    port: 42185
    cipher: aes-256-gcm
    password: "FaTG4zALZru72gxjgSHQ7Jdh"
  - name: "_47"
    type: ss
    server: "46.29.218.6"
    port: 2376
    cipher: aes-256-gcm
    password: "faBAoD54k87UJG7"
  - name: "_57"
    type: ss
    server: "167.88.63.11"
    port: 7307
    cipher: aes-256-gcm
    password: "FoOiGlkAA9yPEGP"
  - name: "_59"
    type: ss
    server: "167.88.63.119"
    port: 7306
    cipher: aes-256-gcm
    password: "FoOiGlkAA9yPEGP"
  - name: "_66"
    type: ss
    server: "167.88.63.119"
    port: 7307
    cipher: aes-256-gcm
    password: "FoOiGlkAA9yPEGP"
  - name: "_68"
    type: ss
    server: "172.99.190.35"
    port: 8090
    cipher: aes-256-gcm
    password: "PCnnH6SQSnfoS27"
  - name: "_69"
    type: ss
    server: "198.57.27.225"
    port: 2375
    cipher: aes-256-gcm
    password: "faBAoD54k87UJG7"
  - name: "_70"
    type: ss
    server: "167.88.63.99"
    port: 7306
    cipher: aes-256-gcm
    password: "FoOiGlkAA9yPEGP"
  - name: "_71"
    type: ss
    server: "167.88.63.82"
    port: 7307
    cipher: aes-256-gcm
    password: "FoOiGlkAA9yPEGP"
  - name: "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_72"
    type: trojan
    server: "t7.ssrsub.com"
    port: 844
    password: "52f31fcb-f948-4f71-bca8-795fdcf7b754"
    sni: "t7.ssrsub.com"
  - name: "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_73"
    type: trojan
    server: "t3.ssrsub.com"
    port: 844
    password: "f5487ee3-aef5-436f-adf9-673b1afe2ff7"
    sni: "t3.ssrsub.com"
  - name: "[10-30]|oslook|ä¸­å›½é¦™æ¸¯/ä¸­å›½å°æ¹¾CNChina/Shenzhen/å¯èƒ½æ˜¯ä¸­è½¬èŠ‚ç‚¹_9"
    type: vmess
    server: "183.232.226.137"
    port: 11110
    uuid: f37bcc5b-6071-3588-a25d-d7747e4c648f
    alterId: 2
    cipher: auto
    tls: false
    network: ws
    ws-path: "/vvv"
    ws-headers:
      Host: "t.me/vpnhat"
  - name: "[10-30]|oslook|ç¾å›½USUSA/San Jose_10"
    type: vmess
    server: "usgia.jjyun.ren"
    port: 88
    uuid: e0dc26b2-9db5-4d92-98d0-b8cc1bfb23ac
    alterId: 10
    cipher: auto
    tls: false
    network: ws
    ws-path: "/jjyun"
  - name: "_03"
    type: ss
    server: "134.195.196.163"
    port: 7307
    cipher: aes-256-gcm
    password: "FoOiGlkAA9yPEGP"
  - name: "_05"
    type: ss
    server: "134.195.196.133"
    port: 7307
    cipher: aes-256-gcm
    password: "FoOiGlkAA9yPEGP"
  - name: "_19"
    type: ss
    server: "167.88.63.108"
    port: 8091
    cipher: aes-256-gcm
    password: "PCnnH6SQSnfoS27"
  - name: "_61"
    type: ss
    server: "38.107.226.149"
    port: 2376
    cipher: aes-256-gcm
    password: "faBAoD54k87UJG7"
proxy-groups:
  - name: Auto - UrlTest
    type: url-test
    proxies:
      - "_15"
      - "_34"
      - "_36"
      - "_64"
      - "_12"
      - "_21"
      - "_35"
      - "_43"
      - "Pool__46"
      - "_47"
      - "_57"
      - "_59"
      - "_66"
      - "_68"
      - "_69"
      - "_70"
      - "_71"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_72"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_73"
      - "[10-30]|oslook|ä¸­å›½é¦™æ¸¯/ä¸­å›½å°æ¹¾CNChina/Shenzhen/å¯èƒ½æ˜¯ä¸­è½¬èŠ‚ç‚¹_9"
      - "[10-30]|oslook|ç¾å›½USUSA/San Jose_10"
      - "_03"
      - "_05"
      - "_19"
      - "_61"
    url: https://cp.cloudflare.com/generate_204
    interval: "600"
    tolerance: "150"
  - name: Proxy
    type: select
    proxies:
      - Auto - UrlTest
      - DIRECT
      - "_15"
      - "_34"
      - "_36"
      - "_64"
      - "_12"
      - "_21"
      - "_35"
      - "_43"
      - "Pool__46"
      - "_47"
      - "_57"
      - "_59"
      - "_66"
      - "_68"
      - "_69"
      - "_70"
      - "_71"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_72"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_73"
      - "[10-30]|oslook|ä¸­å›½é¦™æ¸¯/ä¸­å›½å°æ¹¾CNChina/Shenzhen/å¯èƒ½æ˜¯ä¸­è½¬èŠ‚ç‚¹_9"
      - "[10-30]|oslook|ç¾å›½USUSA/San Jose_10"
      - "_03"
      - "_05"
      - "_19"
      - "_61"
  - name: Domestic
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: Others
    type: select
    proxies:
      - Proxy
      - DIRECT
      - Domestic
  - name: Microsoft
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: Apple
    type: select
    proxies:
      - DIRECT
      - Proxy
      - "_15"
      - "_34"
      - "_36"
      - "_64"
      - "_12"
      - "_21"
      - "_35"
      - "_43"
      - "Pool__46"
      - "_47"
      - "_57"
      - "_59"
      - "_66"
      - "_68"
      - "_69"
      - "_70"
      - "_71"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_72"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_73"
      - "[10-30]|oslook|ä¸­å›½é¦™æ¸¯/ä¸­å›½å°æ¹¾CNChina/Shenzhen/å¯èƒ½æ˜¯ä¸­è½¬èŠ‚ç‚¹_9"
      - "[10-30]|oslook|ç¾å›½USUSA/San Jose_10"
      - "_03"
      - "_05"
      - "_19"
      - "_61"
  - name: Scholar
    type: select
    proxies:
      - DIRECT
      - Proxy
      - "_15"
      - "_34"
      - "_36"
      - "_64"
      - "_12"
      - "_21"
      - "_35"
      - "_43"
      - "Pool__46"
      - "_47"
      - "_57"
      - "_59"
      - "_66"
      - "_68"
      - "_69"
      - "_70"
      - "_71"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_72"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_73"
      - "[10-30]|oslook|ä¸­å›½é¦™æ¸¯/ä¸­å›½å°æ¹¾CNChina/Shenzhen/å¯èƒ½æ˜¯ä¸­è½¬èŠ‚ç‚¹_9"
      - "[10-30]|oslook|ç¾å›½USUSA/San Jose_10"
      - "_03"
      - "_05"
      - "_19"
      - "_61"
  - name: Bilibili
    type: select
    proxies:
      - AsianTV
      - DIRECT
      - "_15"
      - "_34"
      - "_36"
      - "_64"
      - "_12"
      - "_21"
      - "_35"
      - "_43"
      - "Pool__46"
      - "_47"
      - "_57"
      - "_59"
      - "_66"
      - "_68"
      - "_69"
      - "_70"
      - "_71"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_72"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_73"
      - "[10-30]|oslook|ä¸­å›½é¦™æ¸¯/ä¸­å›½å°æ¹¾CNChina/Shenzhen/å¯èƒ½æ˜¯ä¸­è½¬èŠ‚ç‚¹_9"
      - "[10-30]|oslook|ç¾å›½USUSA/San Jose_10"
      - "_03"
      - "_05"
      - "_19"
      - "_61"
  - name: Bahamut
    type: select
    proxies:
      - GlobalTV
      - DIRECT
      - "_15"
      - "_34"
      - "_36"
      - "_64"
      - "_12"
      - "_21"
      - "_35"
      - "_43"
      - "Pool__46"
      - "_47"
      - "_57"
      - "_59"
      - "_66"
      - "_68"
      - "_69"
      - "_70"
      - "_71"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_72"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_73"
      - "[10-30]|oslook|ä¸­å›½é¦™æ¸¯/ä¸­å›½å°æ¹¾CNChina/Shenzhen/å¯èƒ½æ˜¯ä¸­è½¬èŠ‚ç‚¹_9"
      - "[10-30]|oslook|ç¾å›½USUSA/San Jose_10"
      - "_03"
      - "_05"
      - "_19"
      - "_61"
  - name: HBO
    type: select
    proxies:
      - GlobalTV
      - DIRECT
      - "_15"
      - "_34"
      - "_36"
      - "_64"
      - "_12"
      - "_21"
      - "_35"
      - "_43"
      - "Pool__46"
      - "_47"
      - "_57"
      - "_59"
      - "_66"
      - "_68"
      - "_69"
      - "_70"
      - "_71"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_72"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_73"
      - "[10-30]|oslook|ä¸­å›½é¦™æ¸¯/ä¸­å›½å°æ¹¾CNChina/Shenzhen/å¯èƒ½æ˜¯ä¸­è½¬èŠ‚ç‚¹_9"
      - "[10-30]|oslook|ç¾å›½USUSA/San Jose_10"
      - "_03"
      - "_05"
      - "_19"
      - "_61"
  - name: Pornhub
    type: select
    proxies:
      - GlobalTV
      - DIRECT
      - "_15"
      - "_34"
      - "_36"
      - "_64"
      - "_12"
      - "_21"
      - "_35"
      - "_43"
      - "Pool__46"
      - "_47"
      - "_57"
      - "_59"
      - "_66"
      - "_68"
      - "_69"
      - "_70"
      - "_71"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_72"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_73"
      - "[10-30]|oslook|ä¸­å›½é¦™æ¸¯/ä¸­å›½å°æ¹¾CNChina/Shenzhen/å¯èƒ½æ˜¯ä¸­è½¬èŠ‚ç‚¹_9"
      - "[10-30]|oslook|ç¾å›½USUSA/San Jose_10"
      - "_03"
      - "_05"
      - "_19"
      - "_61"
  - name: Netflix
    type: select
    proxies:
      - GlobalTV
      - DIRECT
      - "_15"
      - "_34"
      - "_36"
      - "_64"
      - "_12"
      - "_21"
      - "_35"
      - "_43"
      - "Pool__46"
      - "_47"
      - "_57"
      - "_59"
      - "_66"
      - "_68"
      - "_69"
      - "_70"
      - "_71"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_72"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_73"
      - "[10-30]|oslook|ä¸­å›½é¦™æ¸¯/ä¸­å›½å°æ¹¾CNChina/Shenzhen/å¯èƒ½æ˜¯ä¸­è½¬èŠ‚ç‚¹_9"
      - "[10-30]|oslook|ç¾å›½USUSA/San Jose_10"
      - "_03"
      - "_05"
      - "_19"
      - "_61"
  - name: Disney
    type: select
    proxies:
      - GlobalTV
      - DIRECT
      - "_15"
      - "_34"
      - "_36"
      - "_64"
      - "_12"
      - "_21"
      - "_35"
      - "_43"
      - "Pool__46"
      - "_47"
      - "_57"
      - "_59"
      - "_66"
      - "_68"
      - "_69"
      - "_70"
      - "_71"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_72"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_73"
      - "[10-30]|oslook|ä¸­å›½é¦™æ¸¯/ä¸­å›½å°æ¹¾CNChina/Shenzhen/å¯èƒ½æ˜¯ä¸­è½¬èŠ‚ç‚¹_9"
      - "[10-30]|oslook|ç¾å›½USUSA/San Jose_10"
      - "_03"
      - "_05"
      - "_19"
      - "_61"
  - name: Youtube
    type: select
    disable-udp: true
    proxies:
      - GlobalTV
      - DIRECT
      - "_15"
      - "_34"
      - "_36"
      - "_64"
      - "_12"
      - "_21"
      - "_35"
      - "_43"
      - "Pool__46"
      - "_47"
      - "_57"
      - "_59"
      - "_66"
      - "_68"
      - "_69"
      - "_70"
      - "_71"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_72"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_73"
      - "[10-30]|oslook|ä¸­å›½é¦™æ¸¯/ä¸­å›½å°æ¹¾CNChina/Shenzhen/å¯èƒ½æ˜¯ä¸­è½¬èŠ‚ç‚¹_9"
      - "[10-30]|oslook|ç¾å›½USUSA/San Jose_10"
      - "_03"
      - "_05"
      - "_19"
      - "_61"
  - name: Spotify
    type: select
    proxies:
      - GlobalTV
      - DIRECT
      - "_15"
      - "_34"
      - "_36"
      - "_64"
      - "_12"
      - "_21"
      - "_35"
      - "_43"
      - "Pool__46"
      - "_47"
      - "_57"
      - "_59"
      - "_66"
      - "_68"
      - "_69"
      - "_70"
      - "_71"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_72"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_73"
      - "[10-30]|oslook|ä¸­å›½é¦™æ¸¯/ä¸­å›½å°æ¹¾CNChina/Shenzhen/å¯èƒ½æ˜¯ä¸­è½¬èŠ‚ç‚¹_9"
      - "[10-30]|oslook|ç¾å›½USUSA/San Jose_10"
      - "_03"
      - "_05"
      - "_19"
      - "_61"
  - name: Steam
    type: select
    proxies:
      - DIRECT
      - Proxy
      - "_15"
      - "_34"
      - "_36"
      - "_64"
      - "_12"
      - "_21"
      - "_35"
      - "_43"
      - "Pool__46"
      - "_47"
      - "_57"
      - "_59"
      - "_66"
      - "_68"
      - "_69"
      - "_70"
      - "_71"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_72"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_73"
      - "[10-30]|oslook|ä¸­å›½é¦™æ¸¯/ä¸­å›½å°æ¹¾CNChina/Shenzhen/å¯èƒ½æ˜¯ä¸­è½¬èŠ‚ç‚¹_9"
      - "[10-30]|oslook|ç¾å›½USUSA/San Jose_10"
      - "_03"
      - "_05"
      - "_19"
      - "_61"
  - name: AdBlock
    type: select
    proxies:
      - REJECT
      - DIRECT
      - Proxy
  - name: AsianTV
    type: select
    proxies:
      - DIRECT
      - Proxy
      - "_15"
      - "_34"
      - "_36"
      - "_64"
      - "_12"
      - "_21"
      - "_35"
      - "_43"
      - "Pool__46"
      - "_47"
      - "_57"
      - "_59"
      - "_66"
      - "_68"
      - "_69"
      - "_70"
      - "_71"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_72"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_73"
      - "[10-30]|oslook|ä¸­å›½é¦™æ¸¯/ä¸­å›½å°æ¹¾CNChina/Shenzhen/å¯èƒ½æ˜¯ä¸­è½¬èŠ‚ç‚¹_9"
      - "[10-30]|oslook|ç¾å›½USUSA/San Jose_10"
      - "_03"
      - "_05"
      - "_19"
      - "_61"
  - name: GlobalTV
    type: select
    proxies:
      - Proxy
      - DIRECT
      - "_15"
      - "_34"
      - "_36"
      - "_64"
      - "_12"
      - "_21"
      - "_35"
      - "_43"
      - "Pool__46"
      - "_47"
      - "_57"
      - "_59"
      - "_66"
      - "_68"
      - "_69"
      - "_70"
      - "_71"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_72"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_73"
      - "[10-30]|oslook|ä¸­å›½é¦™æ¸¯/ä¸­å›½å°æ¹¾CNChina/Shenzhen/å¯èƒ½æ˜¯ä¸­è½¬èŠ‚ç‚¹_9"
      - "[10-30]|oslook|ç¾å›½USUSA/San Jose_10"
      - "_03"
      - "_05"
      - "_19"
      - "_61"
  - name: Speedtest
    type: select
    proxies:
      - Proxy
      - DIRECT
      - "_15"
      - "_34"
      - "_36"
      - "_64"
      - "_12"
      - "_21"
      - "_35"
      - "_43"
      - "Pool__46"
      - "_47"
      - "_57"
      - "_59"
      - "_66"
      - "_68"
      - "_69"
      - "_70"
      - "_71"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_72"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_73"
      - "[10-30]|oslook|ä¸­å›½é¦™æ¸¯/ä¸­å›½å°æ¹¾CNChina/Shenzhen/å¯èƒ½æ˜¯ä¸­è½¬èŠ‚ç‚¹_9"
      - "[10-30]|oslook|ç¾å›½USUSA/San Jose_10"
      - "_03"
      - "_05"
      - "_19"
      - "_61"
  - name: Telegram
    type: select
    proxies:
      - Proxy
      - DIRECT
      - "_15"
      - "_34"
      - "_36"
      - "_64"
      - "_12"
      - "_21"
      - "_35"
      - "_43"
      - "Pool__46"
      - "_47"
      - "_57"
      - "_59"
      - "_66"
      - "_68"
      - "_69"
      - "_70"
      - "_71"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_72"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_73"
      - "[10-30]|oslook|ä¸­å›½é¦™æ¸¯/ä¸­å›½å°æ¹¾CNChina/Shenzhen/å¯èƒ½æ˜¯ä¸­è½¬èŠ‚ç‚¹_9"
      - "[10-30]|oslook|ç¾å›½USUSA/San Jose_10"
      - "_03"
      - "_05"
      - "_19"
      - "_61"
  - name: PayPal
    type: select
    proxies:
      - DIRECT
      - Proxy
      - "_15"
      - "_34"
      - "_36"
      - "_64"
      - "_12"
      - "_21"
      - "_35"
      - "_43"
      - "Pool__46"
      - "_47"
      - "_57"
      - "_59"
      - "_66"
      - "_68"
      - "_69"
      - "_70"
      - "_71"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_72"
      - "ğŸ‡·ğŸ‡º Relay_-ğŸ‡·ğŸ‡ºRU_73"
      - "[10-30]|oslook|ä¸­å›½é¦™æ¸¯/ä¸­å›½å°æ¹¾CNChina/Shenzhen/å¯èƒ½æ˜¯ä¸­è½¬èŠ‚ç‚¹_9"
      - "[10-30]|oslook|ç¾å›½USUSA/San Jose_10"
      - "_03"
      - "_05"
      - "_19"
      - "_61"
rules:
